SPIN1   PROC

;; Character #0, GRAM character index 0
        DECLE  $7060  ;.##.....
;       - - -         ;.###....
        DECLE  $4648  ;.#..#...
;       - - -         ;.#...##.
        DECLE  $7846  ;.#...##.
;       - - -         ;.####...
        DECLE  $0060  ;.##.....
;       - - -         ;........

;; Character #1, GRAM character index 1
        DECLE  $7860  ;.##.....
;       - - -         ;.####...
        DECLE  $2624  ;..#..#..
;       - - -         ;..#..##.
        DECLE  $603E  ;..#####.
;       - - -         ;.##.....
        DECLE  $0060  ;.##.....
;       - - -         ;........

;; Character #2, GRAM character index 2
        DECLE  $7060  ;.##.....
;       - - -         ;.###....
        DECLE  $262C  ;..#.##..
;       - - -         ;..#..##.
        DECLE  $605E  ;.#.####.
;       - - -         ;.##.....
        DECLE  $0060  ;.##.....
;       - - -         ;........

;; Character #3, GRAM character index 3
        DECLE  $3030  ;..##....
;       - - -         ;..##....
        DECLE  $4628  ;..#.#...
;       - - -         ;.#...##.
        DECLE  $605E  ;.#.####.
;       - - -         ;.##.....
        DECLE  $0060  ;.##.....
;       - - -         ;........

;; Character #4, GRAM character index 4
        DECLE  $3030  ;..##....
;       - - -         ;..##....
        DECLE  $4648  ;.#..#...
;       - - -         ;.#...##.
        DECLE  $E05E  ;.#.####.
;       - - -         ;###.....
        DECLE  $00C0  ;##......
;       - - -         ;........

;; Character #5, GRAM character index 5
        DECLE  $3030  ;..##....
;       - - -         ;..##....
        DECLE  $4648  ;.#..#...
;       - - -         ;.#...##.
        DECLE  $F0CE  ;##..###.
;       - - -         ;####....
        DECLE  $0000  ;........
;       - - -         ;........

;; Character #6, GRAM character index 6
        DECLE  $3830  ;..##....
;       - - -         ;..###...
        DECLE  $2424  ;..#..#..
;       - - -         ;..#..#..
        DECLE  $FEC6  ;##...##.
;       - - -         ;#######.
        DECLE  $0000  ;........
;       - - -         ;........

;; Character #7, GRAM character index 7
        DECLE  $3830  ;..##....
;       - - -         ;..###...
        DECLE  $2428  ;..#.#...
;       - - -         ;..#..#..
        DECLE  $FEC6  ;##...##.
;       - - -         ;#######.
        DECLE  $0000  ;........
;       - - -         ;........

;; Character #8, GRAM character index 8
        DECLE  $3830  ;..##....
;       - - -         ;..###...
        DECLE  $4428  ;..#.#...
;       - - -         ;.#...#..
        DECLE  $FEC6  ;##...##.
;       - - -         ;#######.
        DECLE  $0000  ;........
;       - - -         ;........

;; Character #9, GRAM character index 9
        DECLE  $3818  ;...##...
;       - - -         ;..###...
        DECLE  $4828  ;..#.#...
;       - - -         ;.#..#...
        DECLE  $C6FE  ;#######.
;       - - -         ;##...##.
        DECLE  $0000  ;........
;       - - -         ;........

;; Character #10, GRAM character index 10
        DECLE  $3818  ;...##...
;       - - -         ;..###...
        DECLE  $4848  ;.#..#...
;       - - -         ;.#..#...
        DECLE  $CEF6  ;####.##.
;       - - -         ;##..###.
        DECLE  $0000  ;........
;       - - -         ;........

;; Character #11, GRAM character index 11
        DECLE  $1818  ;...##...
;       - - -         ;...##...
        DECLE  $C424  ;..#..#..
;       - - -         ;##...#..
        DECLE  $1EE6  ;###..##.
;       - - -         ;...####.
        DECLE  $0000  ;........
;       - - -         ;........

;; Character #12, GRAM character index 12
        DECLE  $1818  ;...##...
;       - - -         ;...##...
        DECLE  $C424  ;..#..#..
;       - - -         ;##...#..
        DECLE  $3EC4  ;##...#..
;       - - -         ;..#####.
        DECLE  $0006  ;.....##.
;       - - -         ;........

;; Character #13, GRAM character index 13
        DECLE  $1818  ;...##...
;       - - -         ;...##...
        DECLE  $C428  ;..#.#...
;       - - -         ;##...#..
        DECLE  $3CC4  ;##...#..
;       - - -         ;..####..
        DECLE  $000C  ;....##..
;       - - -         ;........

;; Character #14, GRAM character index 14
        DECLE  $3C0C  ;....##..
;       - - -         ;..####..
        DECLE  $C848  ;.#..#...
;       - - -         ;##..#...
        DECLE  $0CF4  ;####.#..
;       - - -         ;....##..
        DECLE  $000C  ;....##..
;       - - -         ;........

;; Character #15, GRAM character index 15
        DECLE  $1C0C  ;....##..
;       - - -         ;...###..
        DECLE  $C868  ;.##.#...
;       - - -         ;##..#...
        DECLE  $0CF8  ;#####...
;       - - -         ;....##..
        DECLE  $000C  ;....##..
;       - - -         ;........

;; Character #16, GRAM character index 16
        DECLE  $1C0C  ;....##..
;       - - -         ;...###..
        DECLE  $C868  ;.##.#...
;       - - -         ;##..#...
        DECLE  $1CE8  ;###.#...
;       - - -         ;...###..
        DECLE  $000C  ;....##..
;       - - -         ;........

;; Character #17, GRAM character index 17
        DECLE  $0C0C  ;....##..
;       - - -         ;....##..
        DECLE  $C4F4  ;####.#..
;       - - -         ;##...#..
        DECLE  $1C64  ;.##..#..
;       - - -         ;...###..
        DECLE  $000C  ;....##..
;       - - -         ;........

;; Character #18, GRAM character index 18
        DECLE  $0C0C  ;....##..
;       - - -         ;....##..
        DECLE  $C4F4  ;####.#..
;       - - -         ;##...#..
        DECLE  $3C44  ;.#...#..
;       - - -         ;..####..
        DECLE  $000C  ;....##..
;       - - -         ;........

;; Character #19, GRAM character index 19
        DECLE  $3C0C  ;....##..
;       - - -         ;..####..
        DECLE  $C4C4  ;##...#..
;       - - -         ;##...#..
        DECLE  $1828  ;..#.#...
;       - - -         ;...##...
        DECLE  $0018  ;...##...
;       - - -         ;........

;; Character #20, GRAM character index 20
        DECLE  $3E06  ;.....##.
;       - - -         ;..#####.
        DECLE  $C8C4  ;##...#..
;       - - -         ;##..#...
        DECLE  $1828  ;..#.#...
;       - - -         ;...##...
        DECLE  $0018  ;...##...
;       - - -         ;........

;; Character #21, GRAM character index 21
        DECLE  $1E00  ;........
;       - - -         ;...####.
        DECLE  $C8E6  ;###..##.
;       - - -         ;##..#...
        DECLE  $1828  ;..#.#...
;       - - -         ;...##...
        DECLE  $0018  ;...##...
;       - - -         ;........

;; Character #22, GRAM character index 22
        DECLE  $CE00  ;........
;       - - -         ;##..###.
        DECLE  $48F6  ;####.##.
;       - - -         ;.#..#...
        DECLE  $3828  ;..#.#...
;       - - -         ;..###...
        DECLE  $0018  ;...##...
;       - - -         ;........

;; Character #23, GRAM character index 23
        DECLE  $C600  ;........
;       - - -         ;##...##.
        DECLE  $48FE  ;#######.
;       - - -         ;.#..#...
        DECLE  $3848  ;.#..#...
;       - - -         ;..###...
        DECLE  $0018  ;...##...
;       - - -         ;........

;; Character #24, GRAM character index 24
        DECLE  $C600  ;........
;       - - -         ;##...##.
        DECLE  $44FE  ;#######.
;       - - -         ;.#...#..
        DECLE  $1828  ;..#.#...
;       - - -         ;...##...
        DECLE  $0018  ;...##...
;       - - -         ;........

;; Character #25, GRAM character index 25
        DECLE  $FE00  ;........
;       - - -         ;#######.
        DECLE  $24C6  ;##...##.
;       - - -         ;..#..#..
        DECLE  $3824  ;..#..#..
;       - - -         ;..###...
        DECLE  $0030  ;..##....
;       - - -         ;........

;; Character #26, GRAM character index 26
        DECLE  $FE00  ;........
;       - - -         ;#######.
        DECLE  $24C6  ;##...##.
;       - - -         ;..#..#..
        DECLE  $3828  ;..#.#...
;       - - -         ;..###...
        DECLE  $0030  ;..##....
;       - - -         ;........

;; Character #27, GRAM character index 27
        DECLE  $F000  ;........
;       - - -         ;####....
        DECLE  $26CE  ;##..###.
;       - - -         ;..#..##.
        DECLE  $3028  ;..#.#...
;       - - -         ;..##....
        DECLE  $0030  ;..##....
;       - - -         ;........

;; Character #28, GRAM character index 28
        DECLE  $E0C0  ;##......
;       - - -         ;###.....
        DECLE  $265E  ;.#.####.
;       - - -         ;..#..##.
        DECLE  $3028  ;..#.#...
;       - - -         ;..##....
        DECLE  $0030  ;..##....
;       - - -         ;........

;; Character #29, GRAM character index 29
        DECLE  $6060  ;.##.....
;       - - -         ;.##.....
        DECLE  $465E  ;.#.####.
;       - - -         ;.#...##.
        DECLE  $3028  ;..#.#...
;       - - -         ;..##....
        DECLE  $0030  ;..##....
;       - - -         ;........

;; Character #30, GRAM character index 30
        DECLE  $6060  ;.##.....
;       - - -         ;.##.....
        DECLE  $465E  ;.#.####.
;       - - -         ;.#...##.
        DECLE  $704C  ;.#..##..
;       - - -         ;.###....
        DECLE  $0060  ;.##.....
;       - - -         ;........

;; Character #31, GRAM character index 31
        DECLE  $6060  ;.##.....
;       - - -         ;.##.....
        DECLE  $465E  ;.#.####.
;       - - -         ;.#...##.
        DECLE  $7844  ;.#...#..
;       - - -         ;.####...
        DECLE  $0060  ;.##.....
;       - - -         ;........

        ENDP
